//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "order")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub menu_url: String,
    pub state: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub timestamp: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::order_entry::Entity")]
    OrderEntry,
}

impl Related<super::order_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderEntry.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
