[workspace]

members = [
    "napoli-lib",
    "napoli-server",
    "napoli-server-migrations",
    "napoli-server-persistent-entities",
    "napoli-client-grpc-web",
    "napoli-pain",
    "napoli-pain/src-napoli-app",
]
